language: java
jdk: openjdk8
before_deploy:
  - mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
  - export project_version=$(mvn help:evaluate -N -Dexpression=project.version | grep -v '\[')
deploy:
  provider: releases
  api_key:
    secure: "KLitulBaPudOG1priiTFF9YmnT7p6QC4QhT+sa+N1KB6mmJneiYrz3jB3zC+zw1W+T9YV92TLCig44dzF+UFG5l2rwkOb9TDfyNw3b4Sr4quQbeakpg7v2Q3HBYXMrGoBEvMwIB6/UyB4/8mf7h3x1w0DCkLktREOYngnKWky3v74Qj4jGehy14H/TvH5e/2i3Dr4x+zwKpHQLT/1/plv15Nh/Ydueb5ECgWT84DWi0MGLVN5FiNbhcYTHm6coRRTKNIj31hYdYzn9BMuz5fNoDNiEmkEy0dlWVjct9/kuuY69nCaEVfx7saW3RYU/l9yBp+jx75mcisSgBS4pPjLN65ZApX4SUeRFiwrnJK7Z2D86uI6q+LQyrcg1SIgJaF5BUJzfP+4IXoAQvbK072pW/Ji26aQvH6B+H2+6Dz9OfNkHrXR1ARcbCenb7vGphhbVnkxhbR2lM8tcx7FUYptcILNy/yMNayOxD6RdP6t/cudSLFNgYk5gPPOyCtM//BBsOux/vp0bl/WRZR9Ine3WBEt+5Olw4S0/ogzylGHU9trSYDq6u8c9dHmmV0SBGcV+69Ag7u6EsBxFRlexBK2gIo5VNEHd5GHQA+AvhJ67ES5XAs2z42bzKf8O1rMDsZovePVo9W4Ao8hkCSHt+dno5bhzWBuNVXRcsYXZDM5g4="
  file:
    - target/ebms-adapter-web-$project_version.zip
  skip_cleanup: true
  on:
    repo: java-ebms-adapter/ebms-adapter-web
    branch: master
  name: "$project_version"
addons:
  sonarcloud:
    organization: java-ebms-adapter
    token:
      secure: "QA1Bs0u7DtcInpHLDZLza7v6FSUPVVxSq9pzcBptaUDpUKDj5mSmHYVXtpxIhpCqE554dRKDRWaSufbkD7Lat+uZ7IOjI6I6aB2KimvRWJd9Ta2gjKPXf6sivE5qP6LjqBt+7rXg1mhOlaHKKR73zJkzjp2lkQmKL5rDTmA8wQVDJv260Yu6VgRaDYHvyGliYl0obFG68Obu9cxBH4+s+G8HNmFVG6lCuVj8ZwlCO07NwZW5S/xmtrp+P1219qe9oxmjKianA2cjEt53tMsj0xpRfjDBdPk1Q4LhUQcPR/agfxcmyyE4qCuSZroSNKVWKP8t8UH9hG/w7k4zN9R2J2k1/DM2zG5FHjlbAcUl1WbcRk3Rir7XzaRnN6RS2oHg0yI9U7wU3om99DQRDuoYuV1AlINXkA68GmQ/Uaq/GTG6VOWjhpo3o91ss+W4dEPZptIAMdJOp8qDfcAzJo2bRq6pVRYpwET7mcVZYz2L4TCTOIC3waJNwifBd/P/YF0q8GJy/1m574RA1fFKNJhIzFgju0YiXkeFEeUzOrwpZ4lHY3hgRlH1u0yNT7DYO/rf847oDGitGYNlyGI2a7y9jIbb8JL37Tfa/2r3MIHmBuiSGFwfU2xm6L78R2IQ777u1hwDliznU1T3c/XKjqGIaiYMOYuPfo7mC605JCUoYGI="
script:
  # The following command line builds the project, runs the tests with coverage and then executes the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=java-ebms-adapter_ebms-adapter-web
