language: java
jdk: openjdk8
before_deploy:
  - mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
  - export project_version=$(mvn help:evaluate -N -Dexpression=project.version | grep -v '\[')
deploy:
  provider: releases
  api_key:
    secure: "KLitulBaPudOG1priiTFF9YmnT7p6QC4QhT+sa+N1KB6mmJneiYrz3jB3zC+zw1W+T9YV92TLCig44dzF+UFG5l2rwkOb9TDfyNw3b4Sr4quQbeakpg7v2Q3HBYXMrGoBEvMwIB6/UyB4/8mf7h3x1w0DCkLktREOYngnKWky3v74Qj4jGehy14H/TvH5e/2i3Dr4x+zwKpHQLT/1/plv15Nh/Ydueb5ECgWT84DWi0MGLVN5FiNbhcYTHm6coRRTKNIj31hYdYzn9BMuz5fNoDNiEmkEy0dlWVjct9/kuuY69nCaEVfx7saW3RYU/l9yBp+jx75mcisSgBS4pPjLN65ZApX4SUeRFiwrnJK7Z2D86uI6q+LQyrcg1SIgJaF5BUJzfP+4IXoAQvbK072pW/Ji26aQvH6B+H2+6Dz9OfNkHrXR1ARcbCenb7vGphhbVnkxhbR2lM8tcx7FUYptcILNy/yMNayOxD6RdP6t/cudSLFNgYk5gPPOyCtM//BBsOux/vp0bl/WRZR9Ine3WBEt+5Olw4S0/ogzylGHU9trSYDq6u8c9dHmmV0SBGcV+69Ag7u6EsBxFRlexBK2gIo5VNEHd5GHQA+AvhJ67ES5XAs2z42bzKf8O1rMDsZovePVo9W4Ao8hkCSHt+dno5bhzWBuNVXRcsYXZDM5g4="
  file:
    - target/ebms-adapter-web-$project_version.zip
  skip_cleanup: true
  on:
    repo: java-ebms-adapter/ebms-adapter-web
    branch: master
  name: "$project_version"
addons:
  sonarcloud:
    organization: java-ebms-adapter
    token:
      secure: "WSML0zSdolH22dwKhqp0B4GwniDO9jTk19YGFDPnCsfi4Rue7pG+8pWIVwuPTybfaLLUOyX9zps1VpHoPw6fJ7lAuJ4Z/nVC664YmTYkayg1wZiQjJTqQOxlDzpfWGH9ovyVRXPr5a1SI5L1yfKk+WFF5xrBam/thydcViQbQn6XFhJFfxLiieDArZIjEsAXWHPB2KM91FeieOHb6zhzjJmGri5+k1yQyRkpa6A/lmNbOZKQZt3k5D9ntYhT4ug1rWREZUcCysqTpTrPuQxp0apTfjFe1IlAwyX6hixMH9cWPnOuzcCBWsERCjz1BerV9XAcmLtfF7cBAH7MUeM56i/x0FKQtdC+D3gndG+RF6h7B9IUjySs8WTjyFTGq0rn7OHrKZBj8Z+E7yvI6JynTJn9bJFutvoP97oAgfyxDYqQ7rJRTQ2hWJj5nUdt04jaGnvzNOksbv9Kv6sKpoURDOcVIOZgaLVzfY1wR0wMYh3qq3rSDBDpVXstm8Fmny7TEh+cwkQXKa5rOrmF7lmNhTuwDmz5Xj+ikZlfKclfLDuV5Su4obwU8wixpRBx1hgE+2DLt+w0l0qVkmwu5QqSu0D4McadR8lMsg9u6YM+5EweYHNAhCKleG8vSTlW8a6nUFtiv5pT8TAnDKGyPQJ2OydOV51gpwRaQcF4QKS3Qp8="
script:
  # The following command line builds the project, runs the tests with coverage and then executes the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=java-ebms-adapter_ebms-adapter-web
